---
namespace: test-fleet

helm:
  chart: oci://reg.dev.krd/charts/common-api
  releaseName: notifications-api
  version: 0.2.0

  valuesFiles:
    - base/values.yaml

targetCustomizations:
  - name: development
    clusterSelector: { matchLabels: { env: dev } }
    kustomize: { dir: overlays/development }
    helm: { valuesFiles: [overlays/development/values.yaml] }

dependsOn:
  - name: fleet-test-certs

apiVersion: fleet.cattle.io/v1alpha1
kind: GitRepo
metadata:
  name: fleet-test
  namespace: fleet-default
spec:
  branch: main
  clientSecretName: github-auth-read-only
  repo: https://github.com/ditkrg/test-fleet.git
  targetNamespace: test-fleet
  keepResources: true
  targets:
    - clusterName: dev
